//! C backend for rdgen's arena-owned tagged-union AST representation.

use rdgen_ir::{Element, Grammar, Rule};

/// Emit the C declarations shared by generated parser code and consumers.
pub fn emit_ast(grammar: &Grammar) -> Result<String, String> {
    let mut output = String::from(
        "/* Generated by rdgen; do not edit. */\n"
            .to_owned()
            + "#ifndef RDGEN_AST_H\n#define RDGEN_AST_H\n\n"
            + "#include <stdbool.h>\n#include <stddef.h>\n\n"
            + "typedef struct rdgen_token { const char *text; size_t length; } rdgen_token;\n"
            + "typedef struct rdgen_arena rdgen_arena;\n"
            + "void *rdgen_arena_alloc(rdgen_arena *arena, size_t size);\n\n",
    );

    for rule in &grammar.rules {
        let name = c_type_name(&rule.name);
        output.push_str(&format!("typedef struct {name} {name};\n"));
    }
    output.push('\n');

    for rule in &grammar.rules {
        emit_rule(&mut output, rule)?;
    }
    output.push_str("#endif /* RDGEN_AST_H */\n");
    Ok(output)
}

fn emit_rule(output: &mut String, rule: &Rule) -> Result<(), String> {
    let name = c_type_name(&rule.name);
    output.push_str(&format!("typedef enum {name}_kind {{\n"));
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        output.push_str(&format!("    {name}_{}{}\n", name, variant_name(rule, alternative, index)));
        if index + 1 != rule.alternatives.len() {
            output.push_str(",");
        }
    }
    output.push_str(&format!("}} {name}_kind;\n\n"));
    output.push_str(&format!("struct {name} {{\n    {name}_kind kind;\n    union {{\n"));
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        let variant = variant_name(rule, alternative, index);
        output.push_str(&format!("        struct {{\n"));
        for field in &alternative.constructor.fields {
            let element = find_labeled_element(&alternative.elements, &field.source_label)
                .ok_or_else(|| format!("missing label '{}' in rule '{}'", field.source_label, rule.name))?;
            output.push_str(&format!("            {} {};\n", c_field_type(element), c_field_name(&field.field)));
        }
        output.push_str(&format!("        }} {variant};\n"));
    }
    output.push_str("    } as;\n};\n\n");
    Ok(())
}

fn variant_name(rule: &Rule, alternative: &rdgen_ir::Alternative, index: usize) -> String {
    if alternative.constructor.fields.is_empty() && alternative.constructor.type_name.0 == rule.name {
        format!("ALT{}", index + 1)
    } else {
        c_type_name(&alternative.constructor.type_name.0)
    }
}

fn find_labeled_element<'a>(elements: &'a [Element], label: &str) -> Option<&'a Element> {
    for element in elements {
        match element {
            Element::Rule { label: Some(name), .. }
            | Element::Token { label: Some(name), .. }
            | Element::Literal { label: Some(name), .. } if name == label => return Some(element),
            Element::Group { alternatives, .. } => {
                for alternative in alternatives {
                    if let Some(found) = find_labeled_element(alternative, label) { return Some(found); }
                }
            }
            Element::Repeat { element, .. } => {
                if let Some(found) = find_labeled_element(std::slice::from_ref(element.as_ref()), label) { return Some(found); }
            }
            _ => {}
        }
    }
    None
}

fn c_field_type(element: &Element) -> String {
    match element {
        Element::Rule { rule, .. } => format!("{} *", c_type_name(rule)),
        Element::Token { .. } | Element::Literal { .. } => "rdgen_token".into(),
        Element::Repeat { element, max: Some(1), .. } => format!("struct {{ bool present; {} value; }}", c_field_type(element)),
        Element::Repeat { element, .. } => format!("struct {{ {} *items; size_t length; }}", c_field_type(element)),
        Element::Group { .. } => "bool".into(),
    }
}

fn c_type_name(name: &str) -> String {
    let mut result = String::from("rdgen_");
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_alphanumeric() || character == '_' {
            result.push(character.to_ascii_lowercase());
        } else {
            result.push('_');
        }
        if index == 0 && character.is_ascii_digit() { result.insert(result.len() - 1, '_'); }
    }
    result
}

fn c_field_name(name: &str) -> String {
    let mut result = String::new();
    for character in name.chars() {
        result.push(if character.is_ascii_alphanumeric() || character == '_' { character.to_ascii_lowercase() } else { '_' });
    }
    if result.is_empty() { "field".into() } else { result }
}

/// Emit the C AST header. Parser emission is intentionally separate from the
/// AST ABI while the C recursive-descent control-flow backend is developed.
pub fn emit(grammar: &Grammar) -> Result<String, String> {
    emit_ast(grammar)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rdgen_grammar::compile;

    #[test]
    fn emits_arena_friendly_tagged_unions() {
        let grammar = compile(
            "grammar Expr; expr = value: number => Number(value: value) | left: number, \"+\", right: expr => Add(left: left, right: right); number = digit: \"0\" => Number(digit: digit);",
        ).unwrap();
        let generated = emit_ast(&grammar).unwrap();
        assert!(generated.contains("typedef struct rdgen_expr rdgen_expr;"));
        assert!(generated.contains("rdgen_expr * right;"));
        assert!(generated.contains("rdgen_token digit;"));
        assert!(generated.contains("rdgen_arena_alloc"));
    }
}
