//! C backend for rdgen's arena-owned tagged-union AST representation.

use rdgen_ir::{Element, Grammar, RecoveryStrategy, Rule};

/// Emit the C declarations shared by generated parser code and consumers.
pub fn emit_ast(grammar: &Grammar) -> Result<String, String> {
    let mut output = String::from(
        "/* Generated by rdgen; do not edit. */\n"
            .to_owned()
            + "#ifndef RDGEN_AST_H\n#define RDGEN_AST_H\n\n"
            + "#include <stdbool.h>\n#include <stddef.h>\n\n"
            + "#include <string.h>\n\n"
            + "typedef struct rdgen_token { const char *text; size_t length; } rdgen_token;\n"
            + "typedef struct rdgen_arena rdgen_arena;\n"
            + "void *rdgen_arena_alloc(rdgen_arena *arena, size_t size);\n\n",
    );

    for rule in &grammar.rules {
        let name = c_type_name(&rule.name);
        output.push_str(&format!("typedef struct {name} {name};\n"));
    }
    output.push('\n');

    let mut collection_types = std::collections::HashSet::new();
    for rule in &grammar.rules {
        for alternative in &rule.alternatives {
            for element in &alternative.elements {
                emit_collection_types(&mut output, element, &mut collection_types);
            }
        }
    }
    if !collection_types.is_empty() {
        output.push('\n');
    }

    for rule in &grammar.rules {
        emit_rule(&mut output, rule)?;
    }
    output.push_str("#endif /* RDGEN_AST_H */\n");
    Ok(output)
}

fn emit_rule(output: &mut String, rule: &Rule) -> Result<(), String> {
    let name = c_type_name(&rule.name);
    output.push_str(&format!("typedef enum {name}_kind {{\n"));
    let mut variants = std::collections::HashSet::new();
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        let variant = variant_name(rule, alternative, index);
        if !variants.insert(variant.clone()) {
            return Err(format!("duplicate C AST variant '{}' in rule '{}'", variant, rule.name));
        }
        output.push_str(&format!("    {name}_{variant}\n"));
        if index + 1 != rule.alternatives.len() {
            output.push_str(",");
        }
    }
    output.push_str(&format!("}} {name}_kind;\n\n"));
    output.push_str(&format!("struct {name} {{\n    {name}_kind kind;\n    union {{\n"));
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        let variant = variant_name(rule, alternative, index);
        output.push_str(&format!("        struct {{\n"));
        for field in &alternative.constructor.fields {
            let element = find_labeled_element(&alternative.elements, &field.source_label)
                .ok_or_else(|| format!("missing label '{}' in rule '{}'", field.source_label, rule.name))?;
            output.push_str(&format!("            {} {};\n", c_field_type(element), c_field_name(&field.field)));
        }
        output.push_str(&format!("        }} {variant};\n"));
    }
    output.push_str("    } as;\n};\n\n");
    Ok(())
}

fn variant_name(rule: &Rule, alternative: &rdgen_ir::Alternative, index: usize) -> String {
    if alternative.constructor.fields.is_empty() && alternative.constructor.type_name.0 == rule.name {
        format!("ALT{}", index + 1)
    } else {
        c_type_name(&alternative.constructor.type_name.0)
    }
}

fn find_labeled_element<'a>(elements: &'a [Element], label: &str) -> Option<&'a Element> {
    for element in elements {
        match element {
            Element::Rule { label: Some(name), .. }
            | Element::Token { label: Some(name), .. }
            | Element::Literal { label: Some(name), .. } if name == label => return Some(element),
            Element::Group { label: Some(name), .. } if name == label => return Some(element),
            Element::Repeat { label: Some(name), .. } if name == label => return Some(element),
            Element::Group { alternatives, .. } => {
                for alternative in alternatives {
                    if let Some(found) = find_labeled_element(alternative, label) { return Some(found); }
                }
            }
            Element::Repeat { element, .. } => {
                if let Some(found) = find_labeled_element(std::slice::from_ref(element.as_ref()), label) { return Some(found); }
            }
            _ => {}
        }
    }
    None
}

fn c_field_type(element: &Element) -> String {
    match element {
        Element::Rule { rule, .. } => format!("{} *", c_type_name(rule)),
        Element::Token { .. } | Element::Literal { .. } => "rdgen_token".into(),
        Element::Repeat { element, max: Some(1), .. } => c_collection_name(c_repeat_storage_child(element), true),
        Element::Repeat { element, .. } => c_collection_name(c_repeat_storage_child(element), false),
        Element::Group { .. } => "bool".into(),
    }
}

fn c_value_type(element: &Element) -> String {
    match element {
        Element::Rule { rule, .. } => format!("{} *", c_type_name(rule)),
        Element::Token { .. } | Element::Literal { .. } => "rdgen_token".into(),
        Element::Repeat { element, max: Some(1), .. } => c_collection_name(c_repeat_storage_child(element), true),
        Element::Repeat { element, .. } => c_collection_name(c_repeat_storage_child(element), false),
        Element::Group { .. } => "bool".into(),
    }
}

fn c_collection_key(element: &Element) -> String {
    match element {
        Element::Rule { rule, .. } => c_type_name(rule).trim_start_matches("rdgen_").to_owned(),
        Element::Token { .. } | Element::Literal { .. } => "token".into(),
        Element::Repeat { element, max: Some(1), .. } => format!("optional_{}", c_collection_key(element)),
        Element::Repeat { element, .. } => format!("list_{}", c_collection_key(element)),
        Element::Group { .. } => "group".into(),
    }
}

fn c_collection_name(element: &Element, optional: bool) -> String {
    format!("rdgen_{}_{}", c_collection_key(element), if optional { "optional" } else { "list" })
}

fn emit_collection_types(output: &mut String, element: &Element, emitted: &mut std::collections::HashSet<String>) {
    match element {
        Element::Repeat { element: child, max: Some(1), .. } | Element::Repeat { element: child, max: None, .. } => {
            let value = c_repeat_storage_child(child);
            emit_collection_types(output, value, emitted);
            let optional = matches!(element, Element::Repeat { max: Some(1), .. });
            let name = c_collection_name(value, optional);
            if !emitted.insert(name.clone()) { return; }
            if optional {
                output.push_str(&format!("typedef struct {{ bool present; {} value; }} {};\n", c_value_type(value), name));
            } else {
                output.push_str(&format!("typedef struct {{ {} *items; size_t length; }} {};\n", c_value_type(value), name));
            }
        }
        Element::Group { alternatives, .. } => {
            for alternative in alternatives {
                for child in alternative { emit_collection_types(output, child, emitted); }
            }
        }
        _ => {}
    }
}

fn c_type_name(name: &str) -> String {
    let mut result = String::from("rdgen_");
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_alphanumeric() || character == '_' {
            result.push(character.to_ascii_lowercase());
        } else {
            result.push('_');
        }
        if index == 0 && character.is_ascii_digit() { result.insert(result.len() - 1, '_'); }
    }
    result
}

fn c_field_name(name: &str) -> String {
    let mut result = String::new();
    for character in name.chars() {
        result.push(if character.is_ascii_alphanumeric() || character == '_' { character.to_ascii_lowercase() } else { '_' });
    }
    if result.is_empty() { "field".into() } else { result }
}

/// Emit the C AST header. Parser emission is intentionally separate from the
/// AST ABI while the C recursive-descent control-flow backend is developed.
pub fn emit(grammar: &Grammar) -> Result<String, String> {
    emit_ast(grammar)
}

/// Emit a C parser for the currently supported simple alternative shape.
///
/// Groups and repetitions are intentionally rejected until their C control
/// flow is implemented; silently treating them as empty productions would
/// make the generated parser unsound.
pub fn emit_parser(grammar: &Grammar) -> Result<String, String> {
    for rule in &grammar.rules {
        for alternative in &rule.alternatives {
            if let Some(recovery) = &alternative.recovery {
                if !matches!(recovery.strategy, RecoveryStrategy::SkipUntilSync) {
                    return Err(format!("C parser emitter does not yet support {:?} recovery in rule '{}'", recovery.strategy, rule.name));
                }
            }
        }
    }
    let mut output = emit_ast(grammar)?;
    let guard = "#endif /* RDGEN_AST_H */\n";
    let end = output.rfind(guard).ok_or_else(|| "generated AST is missing its include guard".to_owned())?;
    output.truncate(end);
    output.push_str(&(
        "typedef struct rdgen_parser rdgen_parser;\n"
            .to_owned()
            + "typedef size_t (*rdgen_skip_trivia_fn)(const char *source, size_t position);\n"
            + "typedef bool (*rdgen_scan_terminal_fn)(const char *source, size_t position, const char *name, rdgen_token *token, size_t *end);\n"
            + "typedef bool (*rdgen_match_literal_fn)(const char *source, size_t position, const char *literal, size_t *end);\n"
            + "typedef struct rdgen_error { const char *message; size_t position; } rdgen_error;\n"
            + "struct rdgen_parser { const char *source; size_t length; size_t position; rdgen_arena *arena; rdgen_skip_trivia_fn skip_trivia; rdgen_scan_terminal_fn scan_terminal; rdgen_match_literal_fn match_literal; };\n"
            + "static void rdgen_set_error(rdgen_error *error, const char *message, size_t position) { if (error != NULL) { error->message = message; error->position = position; } }\n"
            + "static void rdgen_skip(rdgen_parser *parser) { if (parser->skip_trivia != NULL) { size_t next = parser->skip_trivia(parser->source, parser->position); if (next >= parser->position && next <= parser->length) parser->position = next; } }\n"
            + "static void rdgen_skip_until_sync(rdgen_parser *parser, const char *const *sync, size_t count) { while (parser->position < parser->length) { for (size_t index = 0; index < count; index++) { size_t length = strlen(sync[index]); if (parser->position + length <= parser->length && strncmp(parser->source + parser->position, sync[index], length) == 0) return; } parser->position++; } }\n"
            + "static bool rdgen_scan_capture(rdgen_parser *parser, const char *name, rdgen_token *token, size_t *end) { return parser->scan_terminal != NULL && parser->scan_terminal(parser->source, parser->position, name, token, end) && *end > parser->position && *end <= parser->length; }\n"
            + "static bool rdgen_match_literal_default(const char *source, size_t position, const char *literal, size_t *end) { size_t length = strlen(literal); if (strncmp(source + position, literal, length) != 0) return false; *end = position + length; return true; }\n"
            + "static bool rdgen_expect_literal(rdgen_parser *parser, const char *literal, rdgen_token *token) { rdgen_skip(parser); size_t end = parser->position; if (parser->match_literal != NULL && parser->match_literal(parser->source, parser->position, literal, &end) && end > parser->position && end <= parser->length) { token->text = parser->source + parser->position; token->length = end - parser->position; parser->position = end; return true; } return false; }\n"
            + "rdgen_parser rdgen_parser_init_with_literal_match(const char *source, size_t length, rdgen_arena *arena, rdgen_skip_trivia_fn skip_trivia, rdgen_scan_terminal_fn scan_terminal, rdgen_match_literal_fn match_literal) { rdgen_parser parser = { source, length, 0, arena, skip_trivia, scan_terminal, match_literal }; return parser; }\n"
            + "rdgen_parser rdgen_parser_init(const char *source, size_t length, rdgen_arena *arena, rdgen_skip_trivia_fn skip_trivia, rdgen_scan_terminal_fn scan_terminal) { return rdgen_parser_init_with_literal_match(source, length, arena, skip_trivia, scan_terminal, rdgen_match_literal_default); }\n\n"
    ));
    for rule in &grammar.rules {
        output.push_str(&format!("static {} *rdgen_parse_{}(rdgen_parser *parser, rdgen_error *error);\n", c_type_name(&rule.name), rule.name));
    }
    output.push('\n');
    for rule in &grammar.rules {
        emit_c_parser_rule(&mut output, rule)?;
    }
    let start = grammar.rules.first().ok_or_else(|| "grammar has no rules".to_owned())?;
    let start_name = c_type_name(&start.name);
    output.push_str(&format!(
        "{start_name} *rdgen_parse(rdgen_parser *parser, rdgen_error *error) {{ {start_name} *node = rdgen_parse_{}(parser, error); if (node == NULL) return NULL; rdgen_skip(parser); if (parser->position != parser->length) {{ rdgen_set_error(error, \"unexpected trailing input\", parser->position); return NULL; }} return node; }}\n\n",
        start.name
    ));
    output.push_str("#endif /* RDGEN_AST_H */\n");
    Ok(output)
}

fn emit_c_parser_rule(output: &mut String, rule: &Rule) -> Result<(), String> {
    let name = c_type_name(&rule.name);
    output.push_str(&format!("static {name} *rdgen_parse_{}(rdgen_parser *parser, rdgen_error *error) {{\n", rule.name));
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        if alternative.elements.iter().any(|element| !is_c_supported_element(element)) {
            return Err(format!("C parser emitter does not yet support grouped or repeated elements in rule '{}'", rule.name));
        }
        output.push_str(&format!("    {{ size_t start_{index} = parser->position;\n"));
        for (element_index, element) in alternative.elements.iter().enumerate() {
            output.push_str(&format!("        {};\n", c_local_declaration(element, element_index)));
            output.push_str(&format!("        {}\n", c_parse_statement(element, element_index, index)?));
        }
        let variant = variant_name(rule, alternative, index);
        output.push_str(&format!("        {name} *node = ({name} *)rdgen_arena_alloc(parser->arena, sizeof(*node));\n        if (node == NULL) {{ rdgen_set_error(error, \"arena allocation failed\", parser->position); return NULL; }}\n        node->kind = {name}_{variant};\n"));
        for field in &alternative.constructor.fields {
            output.push_str(&format!("        node->as.{variant}.{} = {};\n", c_field_name(&field.field), c_local_name_for_label(&alternative.elements, &field.source_label)));
        }
        output.push_str(&format!("        return node;\n    rdgen_alt_fail_{index}:\n        parser->position = start_{index};\n    }}\n"));
    }
    if let Some(recovery) = rule.alternatives.iter().find_map(|alternative| {
        alternative.recovery.as_ref().filter(|point| matches!(point.strategy, RecoveryStrategy::SkipUntilSync))
    }) {
        let sync = recovery.sync_tokens.iter().map(|token| format!("{:?}", token)).collect::<Vec<_>>().join(", ");
        output.push_str(&format!("    {{ const char *sync[] = {{{sync}}}; rdgen_skip_until_sync(parser, sync, {}); }}\n", recovery.sync_tokens.len()));
    }
    output.push_str(&format!("    rdgen_set_error(error, \"no alternative for {}\", parser->position);\n    return NULL;\n}}\n\n", rule.name));
    Ok(())
}

fn is_c_supported_element(element: &Element) -> bool {
    match element {
        Element::Literal { .. } | Element::Token { .. } | Element::Rule { .. } => true,
        Element::Repeat { element, .. } => c_repeat_child(element).is_some_and(is_simple_element),
        Element::Group { alternatives, .. } => c_group_supported(alternatives),
    }
}

fn is_simple_element(element: &Element) -> bool {
    matches!(element, Element::Literal { .. } | Element::Token { .. } | Element::Rule { .. })
}

fn c_local_name_for_label(elements: &[Element], label: &str) -> String {
    elements.iter().enumerate().find_map(|(index, element)| match element {
        Element::Rule { label: Some(name), .. }
        | Element::Token { label: Some(name), .. }
        | Element::Literal { label: Some(name), .. }
        | Element::Group { label: Some(name), .. }
        | Element::Repeat { label: Some(name), .. } if name == label => Some(c_local_name(element, index)),
        _ => None,
    }).unwrap_or_else(|| c_field_name(label))
}

fn c_local_name(element: &Element, index: usize) -> String {
    match element {
        Element::Rule { label: Some(label), .. }
        | Element::Token { label: Some(label), .. }
        | Element::Literal { label: Some(label), .. }
        | Element::Group { label: Some(label), .. }
        | Element::Repeat { label: Some(label), .. } => format!("value_{}", c_field_name(label)),
        _ => format!("element_{index}"),
    }
}

fn c_local_declaration(element: &Element, index: usize) -> String {
    if matches!(element, Element::Repeat { .. }) {
        if matches!(element, Element::Repeat { label: Some(_), .. }) {
            return format!("{} {}", c_field_type(element), c_local_name(element, index));
        }
        return format!("size_t {}_count", c_local_name(element, index));
    }
    if let Some(child) = c_group_child(element) {
        return c_local_declaration(child, index);
    }
    if matches!(element, Element::Group { .. }) {
        return format!("bool {}_matched", c_local_name(element, index));
    }
    format!("{} {}", match element { Element::Rule { rule, .. } => format!("{} *", c_type_name(rule)), _ => "rdgen_token".into() }, c_local_name(element, index))
}

fn c_parse_statement(element: &Element, index: usize, alternative_index: usize) -> Result<String, String> {
    let local = c_local_name(element, index);
    match element {
        Element::Literal { value, .. } => Ok(format!("if (!rdgen_expect_literal(parser, {:?}, &{local})) goto rdgen_alt_fail_{alternative_index};", value)),
        Element::Token { token, .. } => Ok(format!("{{ size_t end_{index} = parser->position; if (parser->scan_terminal == NULL || !parser->scan_terminal(parser->source, parser->position, {:?}, &{local}, &end_{index}) || end_{index} <= parser->position || end_{index} > parser->length) goto rdgen_alt_fail_{alternative_index}; parser->position = end_{index}; }}", token)),
        Element::Rule { rule, .. } => Ok(format!("{local} = rdgen_parse_{}(parser, error); if ({local} == NULL) goto rdgen_alt_fail_{alternative_index};", rule)),
        Element::Group { alternatives, .. } if c_group_child(element).is_some() => c_parse_statement(c_group_child(element).expect("group child checked"), index, alternative_index),
        Element::Group { alternatives, .. } => c_group_statement(alternatives, index, alternative_index, &local),
        Element::Repeat { element: child, max: Some(1), label: Some(_), .. } => c_labeled_repeat_statement(child, index, local, true, alternative_index),
        Element::Repeat { element: child, max: None, label: Some(_), .. } => c_labeled_repeat_statement(child, index, local, false, alternative_index),
        Element::Repeat { element: child, max: Some(1), .. } => Ok(format!("{local}_count = 0; {{ size_t item_start_{index} = parser->position; {} if (parser->position != item_start_{index}) {local}_count = 1; else parser->position = item_start_{index}; }}", c_repeat_probe(c_repeat_child(child).ok_or_else(|| "C optional requires a single-element group".to_owned())?, index)?)),
        Element::Repeat { element: child, max: None, .. } => Ok(format!("{local}_count = 0; for (;;) {{ size_t item_start_{index} = parser->position; {} if (parser->position == item_start_{index}) {{ parser->position = item_start_{index}; break; }} {local}_count++; }}", c_repeat_probe(c_repeat_child(child).ok_or_else(|| "C repetition requires a single-element group".to_owned())?, index)?)),
        _ => Err("unsupported C parser element".into()),
    }
}

fn c_group_child(element: &Element) -> Option<&Element> {
    match element {
        Element::Group { .. } => c_group_atom(element),
        _ => None,
    }
}

fn c_group_supported(alternatives: &[Vec<Element>]) -> bool {
    !alternatives.is_empty() && alternatives.iter().all(|alternative| !alternative.is_empty() && alternative.iter().all(|element| c_group_atom(element).is_some()))
}

fn c_repeat_storage_child(element: &Element) -> &Element {
    c_repeat_child(element).unwrap_or(element)
}

fn c_group_statement(alternatives: &[Vec<Element>], index: usize, alternative_index: usize, local: &str) -> Result<String, String> {
    let mut output = format!("{local}_matched = false; do {{ size_t group_start_{index} = parser->position; ");
    for (group_index, alternative) in alternatives.iter().enumerate() {
        output.push_str(&format!("{{ parser->position = group_start_{index}; bool group_ok_{index}_{group_index} = true; "));
        for (child_index, child) in alternative.iter().enumerate() {
            let child_name = format!("group_item_{index}_{group_index}_{child_index}");
            let failure = format!("group_ok_{index}_{group_index} = false");
            match c_group_atom(child).ok_or_else(|| "C grouped alternatives require simple children".to_owned())? {
                Element::Literal { value, .. } => output.push_str(&format!("rdgen_token {child_name}; if (group_ok_{index}_{group_index} && !rdgen_expect_literal(parser, {:?}, &{child_name})) {failure}; ", value)),
                Element::Token { token, .. } => output.push_str(&format!("rdgen_token {child_name}; size_t group_end_{index}_{group_index}_{child_index} = parser->position; if (group_ok_{index}_{group_index} && (parser->scan_terminal == NULL || !parser->scan_terminal(parser->source, parser->position, {:?}, &{child_name}, &group_end_{index}_{group_index}_{child_index}) || group_end_{index}_{group_index}_{child_index} <= parser->position || group_end_{index}_{group_index}_{child_index} > parser->length)) {failure}; if (group_ok_{index}_{group_index}) parser->position = group_end_{index}_{group_index}_{child_index}; ", token)),
                Element::Rule { rule, .. } => output.push_str(&format!("{} *{child_name} = NULL; if (group_ok_{index}_{group_index}) {{ {child_name} = rdgen_parse_{}(parser, error); if ({child_name} == NULL) {failure}; }} ", c_type_name(rule), rule)),
                _ => return Err("C grouped alternatives require simple children".into()),
            }
        }
        output.push_str(&format!("if (group_ok_{index}_{group_index}) {{ {local}_matched = true; break; }} }} "));
    }
    output.push_str(&format!("}} while (0); if (!{local}_matched) goto rdgen_alt_fail_{alternative_index};"));
    Ok(output)
}

fn c_repeat_child(element: &Element) -> Option<&Element> {
    match element {
        Element::Group { alternatives, .. } if alternatives.len() == 1 && alternatives[0].len() == 1 => c_group_atom(&alternatives[0][0]),
        _ => None,
    }
}

fn c_group_atom(element: &Element) -> Option<&Element> {
    match element {
        Element::Group { alternatives, .. } if alternatives.len() == 1 && alternatives[0].len() == 1 => c_group_atom(&alternatives[0][0]),
        Element::Literal { .. } | Element::Token { .. } | Element::Rule { .. } => Some(element),
        _ => None,
    }
}

fn c_repeat_probe(element: &Element, index: usize) -> Result<String, String> {
    let item = format!("repeat_item_{index}");
    match element {
        Element::Literal { value, .. } => Ok(format!("rdgen_token {item}; if (!rdgen_expect_literal(parser, {:?}, &{item})) parser->position = item_start_{index};", value)),
        Element::Token { token, .. } => Ok(format!("rdgen_token {item}; size_t repeat_end_{index} = parser->position; if (parser->scan_terminal == NULL || !parser->scan_terminal(parser->source, parser->position, {:?}, &{item}, &repeat_end_{index}) || repeat_end_{index} <= parser->position || repeat_end_{index} > parser->length) parser->position = item_start_{index}; else parser->position = repeat_end_{index};", token)),
        Element::Rule { rule, .. } => Ok(format!("{} *{item} = rdgen_parse_{}(parser, error); if ({item} == NULL) parser->position = item_start_{index};", c_type_name(rule), rule)),
        _ => Err("C repetitions currently require a literal, terminal, or rule child".into()),
    }
}

fn c_labeled_repeat_statement(element: &Element, index: usize, local: String, optional: bool, alternative_index: usize) -> Result<String, String> {
    let child = c_repeat_child(element).ok_or_else(|| "C labeled quantifiers require a single-element group".to_owned())?;
    let value_type = c_value_type(child);
    let item = format!("captured_item_{index}");
    let capacity = format!("parser->length - parser->position + 1");
    let mut output = format!("{local}.present = false; ");
    if optional {
        output.push_str(&format!("{{ size_t item_start_{index} = parser->position; {value_type} {item}; bool matched_{index} = false; {} if (parser->position != item_start_{index}) {{ {local}.present = true; {local}.value = {item}; }} else parser->position = item_start_{index}; }}", c_capture_probe(child, index, &item)?));
    } else {
        output = format!("{local}.items = ({value_type} *)rdgen_arena_alloc(parser->arena, ({capacity}) * sizeof(*{local}.items)); {local}.length = 0; if ({local}.items == NULL) {{ rdgen_set_error(error, \"arena allocation failed\", parser->position); goto rdgen_alt_fail_{alternative_index}; }} for (;;) {{ size_t item_start_{index} = parser->position; {value_type} {item}; bool matched_{index} = false; {} if (!matched_{index} || parser->position == item_start_{index}) {{ parser->position = item_start_{index}; break; }} {local}.items[{local}.length++] = {item}; }}", c_capture_probe(child, index, &item)?);
    }
    Ok(output)
}

fn c_capture_probe(element: &Element, index: usize, item: &str) -> Result<String, String> {
    match element {
        Element::Literal { value, .. } => Ok(format!("if (rdgen_expect_literal(parser, {:?}, &{item})) matched_{index} = true; else parser->position = item_start_{index};", value)),
        Element::Token { token, .. } => Ok(format!("size_t capture_end_{index} = parser->position; if (rdgen_scan_capture(parser, {:?}, &{item}, &capture_end_{index})) {{ parser->position = capture_end_{index}; matched_{index} = true; }} else parser->position = item_start_{index};", token)),
        Element::Rule { rule, .. } => Ok(format!("{item} = rdgen_parse_{}(parser, error); if ({item} != NULL) matched_{index} = true; else parser->position = item_start_{index};", rule)),
        _ => Err("C labeled quantifiers currently require a literal, terminal, or rule child".into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rdgen_grammar::compile;

    #[test]
    fn emits_arena_friendly_tagged_unions() {
        let grammar = compile(
            "grammar Expr; expr = value: number => Number(value: value) | left: number, \"+\", right: expr => Add(left: left, right: right); number = digit: \"0\" => Number(digit: digit);",
        ).unwrap();
        let generated = emit_ast(&grammar).unwrap();
        assert!(generated.contains("typedef struct rdgen_expr rdgen_expr;"));
        assert!(generated.contains("rdgen_expr * right;"));
        assert!(generated.contains("rdgen_token digit;"));
        assert!(generated.contains("rdgen_arena_alloc"));
    }

    #[test]
    fn emits_backtracking_parser_for_simple_alternatives() {
        let grammar = compile(
            "grammar Start; start = left: \"a\", right: item => Pair(left: left, right: right); item = \"b\" => Item();",
        ).unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("rdgen_parse_start"));
        assert!(generated.contains("rdgen_parser rdgen_parser_init"));
        assert!(generated.contains("rdgen_match_literal_fn"));
        assert!(generated.contains("rdgen_parser_init_with_literal_match"));
        assert!(generated.contains("rdgen_start *rdgen_parse("));
        assert!(generated.contains("rdgen_expect_literal(parser, \"a\""));
        assert!(generated.contains("node->as.rdgen_pair.left"));
        assert!(generated.contains("rdgen_alt_fail_0:"));
    }

    #[test]
    fn rejects_complex_elements_until_c_control_flow_exists() {
        let grammar = compile("grammar Start; start = ( \"a\", [ \"b\" ] );").unwrap();
        let error = emit_parser(&grammar).unwrap_err();
        assert!(error.contains("does not yet support grouped or repeated elements"));
    }

    #[test]
    fn emits_simple_optional_and_repeated_consumption() {
        let grammar = compile("grammar Start; start = [ \"a\" ], { \"b\" } => Start();").unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("element_0_count = 0"));
        assert!(generated.contains("for (;;)"));
    }

    #[test]
    fn emits_named_collection_types_for_labeled_repetitions() {
        let grammar = compile("grammar Start; start = items: { \"a\" } => Start(items: items);").unwrap();
        let generated = emit_ast(&grammar).unwrap();
        assert!(generated.contains("rdgen_token_list items;"));
        let parser = emit_parser(&grammar).unwrap();
        assert!(parser.contains("value_items.length++"));
    }

    #[test]
    fn emits_single_element_grouped_consumption() {
        let grammar = compile("grammar Start; start = ( \"a\" ) => Start();").unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("rdgen_expect_literal(parser, \"a\""));
    }

    #[test]
    fn emits_nested_single_element_groups() {
        let grammar = compile("grammar Start; start = (( \"a\" )) => Start();").unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("rdgen_expect_literal(parser, \"a\""));
    }

    #[test]
    fn emits_repetition_over_nested_group() {
        let grammar = compile("grammar Start; start = { (( \"a\" )) } => Start();").unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("for (;;)"));
        assert!(generated.contains("rdgen_expect_literal(parser, \"a\""));
    }

    #[test]
    fn emits_multi_element_group_alternatives() {
        let grammar = compile("grammar Start; start = ( \"a\", \"b\" | \"c\", \"d\" ) => Start();").unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("group_start_0"));
        assert!(generated.contains("group_ok_0_1"));
    }

    #[test]
    fn binds_labeled_group_presence_to_c_ast_fields() {
        let grammar = compile("grammar Start; start = pair: ( \"a\", \"b\" ) => Start(pair: pair);").unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("bool value_pair_matched"));
        assert!(generated.contains("node->as.rdgen_start.pair = value_pair"));
    }

    #[test]
    fn emits_skip_until_sync_recovery() {
        let grammar = compile(
            "grammar Statement; statement = \"ok\" => Statement() recover { sync \";\", \"}\"; skip_until_sync; };",
        ).unwrap();
        let generated = emit_parser(&grammar).unwrap();
        assert!(generated.contains("rdgen_skip_until_sync(parser, sync, 2)"));
    }

    #[test]
    fn rejects_unimplemented_recovery_strategies() {
        let grammar = compile(
            "grammar Statement; statement = \"ok\" => Statement() recover { sync \";\"; abort_rule; };",
        ).unwrap();
        let error = emit_parser(&grammar).unwrap_err();
        assert!(error.contains("does not yet support AbortRule recovery"));
    }

    #[test]
    fn rejects_duplicate_c_ast_variants() {
        let grammar = compile("grammar Start; start = \"a\" => Same() | \"b\" => Same();").unwrap();
        let error = emit_ast(&grammar).unwrap_err();
        assert!(error.contains("duplicate C AST variant 'rdgen_same'"));
    }

    #[test]
    fn emits_reference_grammar_ast_headers() {
        for source in [
            include_str!("../../grammars/bascal.bcl.rdg"),
            include_str!("../../grammars/distill.matcher.rdg"),
        ] {
            let grammar = rdgen_grammar::compile(source).unwrap();
            let generated = emit_ast(&grammar).unwrap();
            assert!(generated.contains("#ifndef RDGEN_AST_H"));
            assert!(generated.contains("rdgen_arena_alloc"));
        }
    }

    #[test]
    fn generated_c_parser_executes_with_an_arena() {
        let grammar = rdgen_grammar::compile("grammar Start; start = \"a\", \"b\" => Start();").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let header = directory.path().join("generated.h");
        let source = directory.path().join("main.c");
        let binary = directory.path().join("parser-smoke");
        std::fs::write(&header, emit_parser(&grammar).unwrap()).unwrap();
        std::fs::write(&source, r#"
#include <stdlib.h>
#include "generated.h"
struct rdgen_arena { int unused; };
void *rdgen_arena_alloc(rdgen_arena *arena, size_t size) { (void)arena; return malloc(size); }
int main(void) {
    struct rdgen_arena arena = { 0 };
    rdgen_parser parser = rdgen_parser_init("ab", 2, &arena, NULL, NULL);
    rdgen_error error = { 0 };
    rdgen_start *node = rdgen_parse(&parser, &error);
    return node != NULL && node->kind == rdgen_start_rdgen_start ? 0 : 1;
}
"#).unwrap();
        let compiler = std::process::Command::new("gcc")
            .args(["-std=c11", source.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!("gcc failed: {}", String::from_utf8_lossy(&compiler.stderr));
        }
        let run = std::process::Command::new(&binary).output().unwrap();
        assert!(run.status.success());
    }

    #[test]
    fn generated_c_parser_captures_repeated_tokens() {
        let grammar = rdgen_grammar::compile("grammar Start; start = items: { \"a\" } => Start(items: items);").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let header = directory.path().join("generated.h");
        let source = directory.path().join("main.c");
        let binary = directory.path().join("parser-repeat-smoke");
        std::fs::write(&header, emit_parser(&grammar).unwrap()).unwrap();
        std::fs::write(&source, r#"
#include <stdlib.h>
#include "generated.h"
struct rdgen_arena { int unused; };
void *rdgen_arena_alloc(rdgen_arena *arena, size_t size) { (void)arena; return malloc(size); }
int main(void) {
    struct rdgen_arena arena = { 0 };
    rdgen_parser parser = rdgen_parser_init("aaa", 3, &arena, NULL, NULL);
    rdgen_error error = { 0 };
    rdgen_start *node = rdgen_parse(&parser, &error);
    return node != NULL && node->as.rdgen_start.items.length == 3 ? 0 : 1;
}
"#).unwrap();
        let compiler = std::process::Command::new("gcc")
            .args(["-std=c11", source.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!("gcc failed: {}", String::from_utf8_lossy(&compiler.stderr));
        }
        assert!(std::process::Command::new(&binary).status().unwrap().success());
    }

    #[test]
    fn generated_c_parser_captures_optional_tokens() {
        let grammar = rdgen_grammar::compile("grammar Start; start = item: [ \"a\" ] => Start(item: item);").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let header = directory.path().join("generated.h");
        let source = directory.path().join("main.c");
        let binary = directory.path().join("parser-optional-smoke");
        std::fs::write(&header, emit_parser(&grammar).unwrap()).unwrap();
        std::fs::write(&source, r#"
#include <stdlib.h>
#include "generated.h"
struct rdgen_arena { int unused; };
void *rdgen_arena_alloc(rdgen_arena *arena, size_t size) { (void)arena; return malloc(size); }
int main(void) {
    struct rdgen_arena arena = { 0 };
    rdgen_parser parser = rdgen_parser_init("", 0, &arena, NULL, NULL);
    rdgen_error error = { 0 };
    rdgen_start *node = rdgen_parse(&parser, &error);
    return node != NULL && !node->as.rdgen_start.item.present ? 0 : 1;
}
"#).unwrap();
        let compiler = std::process::Command::new("gcc")
            .args(["-std=c11", source.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!("gcc failed: {}", String::from_utf8_lossy(&compiler.stderr));
        }
        assert!(std::process::Command::new(&binary).status().unwrap().success());
    }
}
