[package]
name = "rdgen"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Recursive-descent parser generator"

[dependencies]
rdgen-grammar = { path = "../rdgen-grammar" }
rdgen-codegen-rust = { path = "../rdgen-codegen-rust" }
rdgen-codegen-c = { path = "../rdgen-codegen-c" }

[[bin]]
name = "rdgen"
path = "src/main.rs"
