//! Rust backend for emitting hand-written-style recursive-descent parsers.

use rdgen_ir::{Element, Grammar, RecoveryStrategy, Rule};

/// Emit the typed AST declarations for a resolved grammar.
///
/// Parser-method emission is intentionally separate: the AST declaration
/// contract must remain usable by every parser backend and can be tested
/// independently of parsing control flow.
pub fn emit_ast(grammar: &Grammar) -> Result<String, String> {
    let mut output = String::from("// Generated by rdgen; do not edit.\n\n");
    output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    output.push_str("pub struct Token(pub String);\n\n");
    for rule in &grammar.rules {
        emit_rule(&mut output, rule)?;
    }
    Ok(output)
}

fn emit_rule(output: &mut String, rule: &Rule) -> Result<(), String> {
    let enum_name = type_name(&rule.name);
    output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    output.push_str(&format!("pub enum {} {{\n", enum_name));
    let mut variants = std::collections::HashSet::new();
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        let variant = variant_name(rule, alternative, index);
        if !variants.insert(variant.clone()) {
            return Err(format!(
                "duplicate AST variant '{}' in rule '{}'",
                variant, rule.name
            ));
        }
        output.push_str("    ");
        output.push_str(&variant);
        if alternative.constructor.fields.is_empty() {
            output.push_str(",\n");
            continue;
        }
        output.push_str(" {\n");
        for field in &alternative.constructor.fields {
            let element = find_labeled_element(&alternative.elements, &field.source_label)
                .ok_or_else(|| {
                    format!(
                        "missing label '{}' in rule '{}'",
                        field.source_label, rule.name
                    )
                })?;
            output.push_str(&format!(
                "        {}: {},\n",
                field_name(&field.field),
                rust_type(element)
            ));
        }
        output.push_str("    },\n");
    }
    output.push_str("}\n\n");
    Ok(())
}

fn variant_name(rule: &Rule, alternative: &rdgen_ir::Alternative, index: usize) -> String {
    if alternative.constructor.fields.is_empty() && alternative.constructor.type_name.0 == rule.name
    {
        format!("Alt{}", index + 1)
    } else {
        type_name(&alternative.constructor.type_name.0)
    }
}

fn find_labeled_element<'a>(elements: &'a [Element], label: &str) -> Option<&'a Element> {
    for element in elements {
        match element {
            Element::Rule {
                label: Some(name), ..
            }
            | Element::Token {
                label: Some(name), ..
            }
            | Element::Literal {
                label: Some(name), ..
            } if name == label => return Some(element),
            Element::Group {
                label: Some(name), ..
            } if name == label => return Some(element),
            Element::Repeat {
                label: Some(name), ..
            } if name == label => return Some(element),
            Element::Group { alternatives, .. } => {
                for alternative in alternatives {
                    if let Some(found) = find_labeled_element(alternative, label) {
                        return Some(found);
                    }
                }
            }
            Element::Repeat { element, .. } => {
                if let Some(found) =
                    find_labeled_element(std::slice::from_ref(element.as_ref()), label)
                {
                    return Some(found);
                }
            }
            _ => {}
        }
    }
    None
}

fn rust_type(element: &Element) -> String {
    match element {
        Element::Rule { rule, .. } => format!("Box<{}>", type_name(rule)),
        Element::Token { .. } | Element::Literal { .. } => "Token".into(),
        Element::Repeat {
            element,
            max: Some(1),
            ..
        } => format!("Option<{}>", rust_type(rust_repeat_child(element))),
        Element::Repeat { element, .. } => {
            format!("Vec<{}>", rust_type(rust_repeat_child(element)))
        }
        Element::Group { .. } => "()".into(),
    }
}

fn rust_repeat_child(element: &Element) -> &Element {
    match element {
        Element::Group { alternatives, .. }
            if alternatives.len() == 1 && alternatives[0].len() == 1 =>
        {
            &alternatives[0][0]
        }
        _ => element,
    }
}

fn type_name(name: &str) -> String {
    let mut result = String::new();
    for part in name.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.extend(first.to_uppercase());
        }
        result.extend(chars);
    }
    if result.is_empty() {
        "Anonymous".into()
    } else {
        result
    }
}

fn field_name(name: &str) -> String {
    match name {
        "type" | "match" | "ref" | "self" | "crate" | "super" | "mod" | "move" => {
            format!("r#{}", name)
        }
        _ => name.to_owned(),
    }
}

/// Emit a Rust parser from the resolved grammar IR.
pub fn emit(grammar: &Grammar) -> Result<String, String> {
    let mut output = emit_ast(grammar)?;
    output.push_str(&emit_parser(grammar)?);
    Ok(output)
}

/// Emit parser control flow for the currently supported core element set.
pub fn emit_parser(grammar: &Grammar) -> Result<String, String> {
    let start = grammar
        .rules
        .first()
        .ok_or_else(|| "grammar has no rules".to_owned())?;
    let mut output = String::from(
        "#[derive(Clone, Debug, PartialEq)]\n"
            .to_owned() + "pub struct ParseError { pub message: String, pub position: usize }\n\n"
            + "pub type TerminalScanner = fn(&str, usize, &str) -> Option<(Token, usize)>;\n\n"
            + "fn missing_terminal(_: &str, _: usize, _: &str) -> Option<(Token, usize)> { None }\n\n"
            + "pub type TriviaSkipper = fn(&str, usize) -> usize;\n\n"
            + "fn skip_no_trivia(_: &str, position: usize) -> usize { position }\n\n"
            + "pub type LiteralMatcher = fn(&str, usize, &str) -> Option<usize>;\n\n"
            + "fn match_literal(source: &str, position: usize, literal: &str) -> Option<usize> { source[position..].starts_with(literal).then_some(position + literal.len()) }\n\n"
            + "#[allow(dead_code)]\n"
            + "pub struct Parser<'a> { source: &'a str, position: usize, scan_terminal: TerminalScanner, skip_trivia: TriviaSkipper, match_literal: LiteralMatcher }\n\n"
            + "#[allow(dead_code)]\n"
            + "impl<'a> Parser<'a> {\n"
            + "    pub fn new(source: &'a str) -> Self { Self::with_terminal_scanner(source, missing_terminal) }\n"
            + "    pub fn with_terminal_scanner(source: &'a str, scan_terminal: TerminalScanner) -> Self { Self::with_scanner_and_trivia(source, scan_terminal, skip_no_trivia) }\n"
            + "    pub fn with_scanner_and_trivia(source: &'a str, scan_terminal: TerminalScanner, skip_trivia: TriviaSkipper) -> Self { Self::with_lexical_config(source, scan_terminal, skip_trivia, match_literal) }\n"
            + "    pub fn with_lexical_config(source: &'a str, scan_terminal: TerminalScanner, skip_trivia: TriviaSkipper, match_literal: LiteralMatcher) -> Self { Self { source, position: 0, scan_terminal, skip_trivia, match_literal } }\n"
            + "    pub fn parse(&mut self) -> Result<" + &type_name(&start.name) + ", ParseError> { let value = self.parse_" + &start.name + "()?; self.skip_trivia(); if self.position != self.source.len() { return Err(ParseError { message: \"unexpected trailing input\".into(), position: self.position }); } Ok(value) }\n"
            + "    fn skip_trivia(&mut self) { let next = (self.skip_trivia)(self.source, self.position); if next >= self.position && next <= self.source.len() && self.source.is_char_boundary(next) { self.position = next; } }\n"
            + "    fn skip_until_sync(&mut self, sync: &[&str]) { while self.position < self.source.len() { if sync.iter().any(|literal| self.source[self.position..].starts_with(literal)) { return; } if let Some(character) = self.source[self.position..].chars().next() { self.position += character.len_utf8(); } else { return; } } }\n"
            + "    fn expect_literal(&mut self, literal: &str) -> Result<Token, ParseError> {\n"
            + "        self.skip_trivia();\n"
            + "        if self.position <= self.source.len() && self.source.is_char_boundary(self.position) {\n"
            + "            if let Some(end) = (self.match_literal)(self.source, self.position, literal) {\n"
            + "                if end <= self.source.len() && self.source.is_char_boundary(end) { self.position = end; return Ok(Token(literal.to_owned())); }\n"
            + "            }\n"
            + "        }\n"
            + "        Err(ParseError { message: format!(\"expected {:?}\", literal), position: self.position })\n"
            + "    }\n"
            + "    fn expect_terminal(&mut self, name: &str) -> Result<Token, ParseError> {\n"
            + "        self.skip_trivia();\n"
            + "        match (self.scan_terminal)(self.source, self.position, name) {\n"
            + "            Some((token, end)) if end > self.position && end <= self.source.len() && self.source.is_char_boundary(self.position) && self.source.is_char_boundary(end) => { self.position = end; Ok(token) }\n"
            + "            _ => Err(ParseError { message: format!(\"expected terminal {:?}\", name), position: self.position }),\n"
            + "        }\n"
            + "    }\n",
    );
    for rule in &grammar.rules {
        emit_parser_rule(&mut output, rule)?;
    }
    output.push_str("}\n");
    Ok(output)
}

fn emit_parser_rule(output: &mut String, rule: &Rule) -> Result<(), String> {
    output.push_str(&format!(
        "    fn parse_{}(&mut self) -> Result<{}, ParseError> {{\n",
        rule.name,
        type_name(&rule.name)
    ));
    for (index, alternative) in rule.alternatives.iter().enumerate() {
        output.push_str("        let start = self.position;\n");
        output.push_str(&format!(
            "        let attempt: Result<{}, ParseError> = (|| {{\n",
            type_name(&rule.name)
        ));
        for (index, element) in alternative.elements.iter().enumerate() {
            let variable = element_variable(element, index);
            emit_element_binding(output, element, &variable, "            ")?;
        }
        output.push_str(&format!(
            "            Ok({}::{}{})\n",
            type_name(&rule.name),
            variant_name(rule, alternative, index),
            emit_constructor_fields(alternative)?
        ));
        output.push_str("        })();\n");
        output.push_str("        match attempt { Ok(value) => return Ok(value), Err(_) => self.position = start }\n");
    }
    if let Some(recovery) = rule.alternatives.iter().find_map(|alternative| {
        (alternative
            .recovery
            .as_ref()
            .is_some_and(|point| matches!(point.strategy, RecoveryStrategy::SkipUntilSync)))
        .then(|| {
            alternative
                .recovery
                .as_ref()
                .expect("recovery point checked")
        })
    }) {
        let sync = recovery
            .sync_tokens
            .iter()
            .map(|token| format!("{:?}", token))
            .collect::<Vec<_>>()
            .join(", ");
        output.push_str(&format!("        self.skip_until_sync(&[{}]);\n", sync));
    }
    output.push_str(&format!("        Err(ParseError {{ message: \"no alternative for {}\".into(), position: self.position }})\n", rule.name));
    output.push_str("    }\n");
    Ok(())
}

fn emit_element_parse(element: &Element) -> Result<String, String> {
    match element {
        Element::Literal { value, .. } => Ok(format!("self.expect_literal({:?})?", value)),
        Element::Token { token, .. } => Ok(format!("self.expect_terminal({:?})?", token)),
        Element::Rule { rule, .. } => Ok(format!("Box::new(self.parse_{}()?)", rule)),
        Element::Group { .. } | Element::Repeat { .. } => emit_element_expression(element),
    }
}

fn emit_element_binding(
    output: &mut String,
    element: &Element,
    variable: &str,
    indent: &str,
) -> Result<(), String> {
    match element {
        Element::Repeat {
            element: child,
            max: None,
            ..
        } => {
            let child = simple_group_element(child.as_ref()).unwrap_or(child.as_ref());
            output.push_str(&format!("{}let mut {} = Vec::new();\n", indent, variable));
            output.push_str(&format!(
                "{}loop {{\n{}    let item_start = self.position;\n",
                indent, indent
            ));
            output.push_str(&format!(
                "{}    let item = match (|| -> Result<_, ParseError> {{ Ok({}) }})() {{\n",
                indent,
                emit_element_parse(child)?
            ));
            output.push_str(&format!("{}        Ok(item) => item,\n{}        Err(_) => {{ self.position = item_start; break; }}\n{}    }};\n", indent, indent, indent));
            output.push_str(&format!(
                "{}    if self.position == item_start {{ break; }}\n{}    {}.push(item);\n{} }}\n",
                indent, indent, variable, indent
            ));
            return Ok(());
        }
        Element::Repeat {
            element: child,
            max: Some(1),
            ..
        } => {
            let child = simple_group_element(child.as_ref()).unwrap_or(child.as_ref());
            output.push_str(&format!(
                "{}let {} = {{\n{}    let optional_start = self.position;\n",
                indent, variable, indent
            ));
            output.push_str(&format!(
                "{}    match (|| -> Result<_, ParseError> {{ Ok({}) }})() {{\n",
                indent,
                emit_element_parse(child)?
            ));
            output.push_str(&format!("{}        Ok(value) => Some(value),\n{}        Err(_) => {{ self.position = optional_start; None }}\n{}    }}\n{} }};\n", indent, indent, indent, indent));
            return Ok(());
        }
        Element::Repeat { .. } => {
            return Err("parser emitter only supports optional and zero-or-more repetitions".into())
        }
        Element::Group { alternatives, .. } => {
            if alternatives
                .iter()
                .any(|alternative| alternative.len() != 1)
            {
                output.push_str(&format!(
                    "{}let {} = {};\n",
                    indent,
                    variable,
                    emit_group_expression(element)?
                ));
                return Ok(());
            }
            let first = alternatives
                .iter()
                .find_map(|alternative| alternative.first());
            if first.is_none() {
                output.push_str(&format!(
                    "{}let {} = {};\n",
                    indent,
                    variable,
                    emit_group_expression(element)?
                ));
                return Ok(());
            }
            let first = first.expect("checked above");
            let expected_type = rust_type(first);
            if alternatives.iter().any(|alternative| {
                alternative
                    .first()
                    .map_or(true, |element| rust_type(element) != expected_type)
            }) {
                output.push_str(&format!(
                    "{}let {} = {};\n",
                    indent,
                    variable,
                    emit_group_expression(element)?
                ));
                return Ok(());
            }
            output.push_str(&format!(
                "{}let {} = {{\n{}    let group_result: Result<_, ParseError> = (|| {{\n",
                indent, variable, indent
            ));
            for alternative in alternatives {
                let child = &alternative[0];
                output.push_str(&format!(
                    "{}        let group_start = self.position;\n",
                    indent
                ));
                output.push_str(&format!(
                    "{}        let group_attempt = (|| -> Result<_, ParseError> {{ Ok({}) }})();\n",
                    indent,
                    emit_element_parse(child)?
                ));
                output.push_str(&format!("{}        match group_attempt {{ Ok(value) => return Ok(value), Err(_) => self.position = group_start }}\n", indent));
            }
            output.push_str(&format!("{}        Err(ParseError {{ message: \"no grouped alternative\".into(), position: self.position }})\n{}    }})();\n{}    match group_result {{ Ok(value) => value, Err(error) => return Err(error) }}\n{} }};\n", indent, indent, indent, indent));
            return Ok(());
        }
        _ => {
            output.push_str(&format!(
                "{}let {} = {};\n",
                indent,
                variable,
                emit_element_parse(element)?
            ));
            return Ok(());
        }
    }
}

fn simple_group_element(element: &Element) -> Option<&Element> {
    match element {
        Element::Group { alternatives, .. }
            if alternatives.len() == 1 && alternatives[0].len() == 1 =>
        {
            Some(&alternatives[0][0])
        }
        _ => Some(element),
    }
}

fn emit_group_expression(element: &Element) -> Result<String, String> {
    let Element::Group { alternatives, .. } = element else {
        return Err("expected grouped element".into());
    };
    if alternatives.is_empty() {
        return Err("empty group".into());
    }
    let mut output = String::from("{ let group_result: Result<(), ParseError> = (|| { ");
    for alternative in alternatives {
        output.push_str("let group_start = self.position; ");
        output.push_str("let group_attempt = (|| -> Result<(), ParseError> { ");
        for child in alternative {
            output.push_str(&format!("let _ = {}; ", emit_element_parse(child)?));
        }
        output.push_str("Ok(()) })(); ");
        output.push_str("match group_attempt { Ok(value) => return Ok(value), Err(_) => self.position = group_start } ");
    }
    output.push_str("Err(ParseError { message: \"no grouped alternative\".into(), position: self.position }) })(); match group_result { Ok(value) => value, Err(error) => return Err(error) } }");
    Ok(output)
}

fn emit_element_expression(element: &Element) -> Result<String, String> {
    match element {
        Element::Group { .. } => emit_group_expression(element),
        Element::Repeat { element: child, max: None, .. } => {
            let mut output = String::from("{ let mut values = Vec::new(); loop { let item_start = self.position; ");
            output.push_str(&format!("let item = match (|| -> Result<_, ParseError> {{ Ok({}) }})() {{ ", emit_element_expression(child)?));
            output.push_str("Ok(item) => item, Err(_) => { self.position = item_start; break; } }; ");
            output.push_str("if self.position == item_start { break; } values.push(item); } values }");
            Ok(output)
        }
        Element::Repeat { element: child, max: Some(1), .. } => Ok(format!(
            "{{ let optional_start = self.position; match (|| -> Result<_, ParseError> {{ Ok({}) }})() {{ Ok(value) => Some(value), Err(_) => {{ self.position = optional_start; None }} }} }}",
            emit_element_expression(child)?
        )),
        Element::Repeat { .. } => Err("parser emitter only supports optional and zero-or-more repetitions".into()),
        Element::Literal { value, .. } => Ok(format!("self.expect_literal({:?})?", value)),
        Element::Token { token, .. } => Ok(format!("self.expect_terminal({:?})?", token)),
        Element::Rule { rule, .. } => Ok(format!("Box::new(self.parse_{}()?)", rule)),
    }
}

fn element_variable(element: &Element, index: usize) -> String {
    let label = match element {
        Element::Rule { label, .. }
        | Element::Token { label, .. }
        | Element::Literal { label, .. } => label.as_deref(),
        Element::Group { label, .. } | Element::Repeat { label, .. } => label.as_deref(),
    };
    label.map_or_else(|| format!("_element_{}", index), field_name)
}

fn emit_constructor_fields(alternative: &rdgen_ir::Alternative) -> Result<String, String> {
    if alternative.constructor.fields.is_empty() {
        return Ok(String::new());
    }
    let mut output = String::from(" { ");
    for (index, field) in alternative.constructor.fields.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }
        output.push_str(&format!(
            "{}: {}",
            field_name(&field.field),
            field_name(&field.source_label)
        ));
    }
    output.push_str(" }");
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rdgen_grammar::compile;

    #[test]
    fn emits_concrete_typed_ast_variants_and_recursive_boxes() {
        let grammar = compile(
            "grammar Expr; expr = value: number => Number(value: value) | left: number, \"+\", right: expr => Add(left: left, right: right); number = digit: \"0\" => Number(digit: digit);",
        ).unwrap();
        let generated = emit_ast(&grammar).unwrap();
        assert!(generated.contains("pub enum Expr"));
        assert!(generated.contains("Number {"));
        assert!(generated.contains("value: Box<Number>"));
        assert!(generated.contains("right: Box<Expr>"));
        assert!(generated.contains("digit: Token"));
    }

    #[test]
    fn emits_literal_parser_control_flow_and_constructor_assembly() {
        let grammar = compile(
            "grammar Expr; expr = value: number => Number(value: value); number = digit: \"0\" => Number(digit: digit);",
        ).unwrap();
        let generated = emit(&grammar).unwrap();
        assert!(generated.contains("pub struct Parser<'a>"));
        assert!(generated.contains("self.expect_literal(\"0\")?"));
        assert!(generated.contains("Ok(Number::Number { digit: digit })"));
        assert!(generated.contains("pub type TerminalScanner = fn(&str, usize, &str)"));
        assert!(generated.contains("pub type TriviaSkipper = fn(&str, usize) -> usize"));
        assert!(generated.contains("with_scanner_and_trivia"));
        assert!(
            generated.contains("pub type LiteralMatcher = fn(&str, usize, &str) -> Option<usize>")
        );
        assert!(generated.contains("with_lexical_config"));
        assert!(generated.contains("unexpected trailing input"));
    }

    #[test]
    fn emits_optional_and_repeated_simple_elements() {
        let grammar =
            compile("grammar List; list = head: \"x\", { \"+\" } => List(head: head);").unwrap();
        let generated = emit(&grammar).unwrap();
        assert!(generated.contains("let mut _element_1 = Vec::new()"));
        assert!(generated.contains("if self.position == item_start"));
    }

    #[test]
    fn emits_labeled_repetition_fields() {
        let grammar =
            compile("grammar List; list = items: { \"x\" } => List(items: items);").unwrap();
        let generated = emit(&grammar).unwrap();
        assert!(generated.contains("items: Vec<Token>"));
        assert!(generated.contains("let mut items = Vec::new()"));
        assert!(generated.contains("List::List { items: items }"));
    }

    #[test]
    fn emits_multi_element_grouped_sequences() {
        let grammar = compile("grammar Pair; pair = ( \"a\", \"b\" ) | ( \"c\", \"d\" );").unwrap();
        let generated = emit(&grammar).unwrap();
        assert!(generated.contains("let group_attempt = (|| -> Result<(), ParseError>"));
        assert!(generated.contains("self.expect_literal(\"a\")?"));
        assert!(generated.contains("self.expect_literal(\"b\")?"));
    }

    #[test]
    fn synthesizes_unique_variants_for_unannotated_alternatives() {
        let grammar = compile("grammar Suffix; suffix = \"%\" | \"$\";").unwrap();
        let generated = emit_ast(&grammar).unwrap();
        assert!(generated.contains("Alt1,"));
        assert!(generated.contains("Alt2,"));
    }

    #[test]
    fn emits_skip_until_sync_recovery() {
        let grammar = compile(
            "grammar Statement; statement = \"ok\" => Statement() recover { sync \";\", \"}\"; skip_until_sync; };",
        ).unwrap();
        let generated = emit(&grammar).unwrap();
        assert!(generated.contains("fn skip_until_sync(&mut self, sync: &[&str])"));
        assert!(generated.contains("self.skip_until_sync(&[\";\", \"}\"]);"));
    }

    #[test]
    fn generated_rust_parser_executes() {
        let grammar = compile("grammar Start; start = \"a\" => Start();").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let generated = directory.path().join("generated.rs");
        let wrapper = directory.path().join("main.rs");
        let binary = directory.path().join("parser-smoke");
        std::fs::write(&generated, emit(&grammar).unwrap()).unwrap();
        std::fs::write(
            &wrapper,
            format!(
                "include!({:?});\nfn main() {{ let mut parser = Parser::new(\"a\"); assert!(parser.parse().is_ok()); let mut trailing = Parser::new(\"ab\"); let error = trailing.parse().unwrap_err(); assert_eq!(error.message, \"unexpected trailing input\"); assert_eq!(error.position, 1); }}\n",
                generated.to_str().unwrap()
            ),
        )
        .unwrap();
        let compiler = std::process::Command::new("rustc")
            .args([wrapper.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!(
                "rustc failed: {}",
                String::from_utf8_lossy(&compiler.stderr)
            );
        }
        assert!(std::process::Command::new(&binary)
            .status()
            .unwrap()
            .success());
    }

    #[test]
    fn generated_rust_parser_uses_terminal_and_trivia_callbacks() {
        let grammar = compile("grammar Start; start = item: digit => Start(item: item);").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let generated = directory.path().join("generated.rs");
        let wrapper = directory.path().join("main.rs");
        let binary = directory.path().join("parser-callbacks");
        std::fs::write(&generated, emit(&grammar).unwrap()).unwrap();
        std::fs::write(
            &wrapper,
            format!(
                "include!({:?});\nfn scan_digit(source: &str, position: usize, name: &str) -> Option<(Token, usize)> {{ if name != \"digit\" || !source[position..].starts_with(\"7\") {{ None }} else {{ Some((Token(\"7\".into()), position + 1)) }} }}\nfn skip_spaces(source: &str, position: usize) -> usize {{ source[position..].chars().take_while(|character| character.is_whitespace()).map(char::len_utf8).sum::<usize>() + position }}\nfn main() {{ let mut parser = Parser::with_scanner_and_trivia(\" 7\", scan_digit, skip_spaces); assert!(parser.parse().is_ok()); }}\n",
                generated.to_str().unwrap()
            ),
        )
        .unwrap();
        let compiler = std::process::Command::new("rustc")
            .args([wrapper.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!("rustc failed: {}", String::from_utf8_lossy(&compiler.stderr));
        }
        assert!(std::process::Command::new(&binary).status().unwrap().success());
    }

    #[test]
    fn generated_rust_parser_uses_literal_matcher_callback() {
        let grammar = compile("grammar Start; start = \"IF\" => Start();").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let generated = directory.path().join("generated.rs");
        let wrapper = directory.path().join("main.rs");
        let binary = directory.path().join("parser-literal-callback");
        std::fs::write(&generated, emit(&grammar).unwrap()).unwrap();
        std::fs::write(
            &wrapper,
            format!(
                "include!({:?});\nfn match_keyword(source: &str, position: usize, literal: &str) -> Option<usize> {{ let candidate = source.get(position..position + literal.len())?; candidate.eq_ignore_ascii_case(literal).then_some(position + literal.len()) }}\nfn main() {{ let mut parser = Parser::with_lexical_config(\"if\", missing_terminal, skip_no_trivia, match_keyword); assert!(parser.parse().is_ok()); }}\n",
                generated.to_str().unwrap()
            ),
        )
        .unwrap();
        let compiler = std::process::Command::new("rustc")
            .args([wrapper.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!("rustc failed: {}", String::from_utf8_lossy(&compiler.stderr));
        }
        assert!(std::process::Command::new(&binary).status().unwrap().success());
    }

    #[test]
    fn generated_rust_parser_captures_repeated_literals() {
        let grammar = compile("grammar Start; items = values: { \"x\" } => Start(values: values);").unwrap();
        let directory = tempfile::tempdir().unwrap();
        let generated = directory.path().join("generated.rs");
        let wrapper = directory.path().join("main.rs");
        let binary = directory.path().join("parser-repeat");
        std::fs::write(&generated, emit(&grammar).unwrap()).unwrap();
        std::fs::write(
            &wrapper,
            format!(
                "include!({:?});\nfn main() {{ let mut parser = Parser::new(\"xxx\"); let value = parser.parse().unwrap(); match value {{ Items::Start {{ values }} => assert_eq!(values.len(), 3), }} }}\n",
                generated.to_str().unwrap()
            ),
        )
        .unwrap();
        let compiler = std::process::Command::new("rustc")
            .args([wrapper.to_str().unwrap(), "-o", binary.to_str().unwrap()])
            .output()
            .unwrap();
        if !compiler.status.success() {
            panic!("rustc failed: {}", String::from_utf8_lossy(&compiler.stderr));
        }
        assert!(std::process::Command::new(&binary).status().unwrap().success());
    }
}
