//! Rust backend for emitting hand-written-style recursive-descent parsers.

use rdgen_ir::{Element, Grammar, Rule};

/// Emit the typed AST declarations for a resolved grammar.
///
/// Parser-method emission is intentionally separate: the AST declaration
/// contract must remain usable by every parser backend and can be tested
/// independently of parsing control flow.
pub fn emit_ast(grammar: &Grammar) -> Result<String, String> {
    let mut output = String::from("// Generated by rdgen; do not edit.\n\n");
    output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    output.push_str("pub struct Token(pub String);\n\n");
    for rule in &grammar.rules {
        emit_rule(&mut output, rule)?;
    }
    Ok(output)
}

fn emit_rule(output: &mut String, rule: &Rule) -> Result<(), String> {
    let enum_name = type_name(&rule.name);
    output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    output.push_str(&format!("pub enum {} {{\n", enum_name));
    let mut variants = std::collections::HashSet::new();
    for alternative in &rule.alternatives {
        let variant = type_name(&alternative.constructor.type_name.0);
        if !variants.insert(variant.clone()) {
            return Err(format!("duplicate AST variant '{}' in rule '{}'", variant, rule.name));
        }
        output.push_str("    ");
        output.push_str(&variant);
        if alternative.constructor.fields.is_empty() {
            output.push_str(",\n");
            continue;
        }
        output.push_str(" {\n");
        for field in &alternative.constructor.fields {
            let element = find_labeled_element(&alternative.elements, &field.source_label)
                .ok_or_else(|| format!("missing label '{}' in rule '{}'", field.source_label, rule.name))?;
            output.push_str(&format!("        {}: {},\n", field_name(&field.field), rust_type(element)));
        }
        output.push_str("    },\n");
    }
    output.push_str("}\n\n");
    Ok(())
}

fn find_labeled_element<'a>(elements: &'a [Element], label: &str) -> Option<&'a Element> {
    for element in elements {
        match element {
            Element::Rule { label: Some(name), .. }
            | Element::Token { label: Some(name), .. }
            | Element::Literal { label: Some(name), .. } if name == label => return Some(element),
            Element::Group { alternatives, .. } => {
                for alternative in alternatives {
                    if let Some(found) = find_labeled_element(alternative, label) { return Some(found); }
                }
            }
            Element::Repeat { element, .. } => {
                if let Some(found) = find_labeled_element(std::slice::from_ref(element.as_ref()), label) { return Some(found); }
            }
            _ => {}
        }
    }
    None
}

fn rust_type(element: &Element) -> String {
    match element {
        Element::Rule { rule, .. } => format!("Box<{}>", type_name(rule)),
        Element::Token { .. } | Element::Literal { .. } => "Token".into(),
        Element::Repeat { element, .. } => format!("Vec<{}>", rust_type(element)),
        Element::Group { .. } => "Vec<Token>".into(),
    }
}

fn type_name(name: &str) -> String {
    let mut result = String::new();
    for part in name.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() { result.extend(first.to_uppercase()); }
        result.extend(chars);
    }
    if result.is_empty() { "Anonymous".into() } else { result }
}

fn field_name(name: &str) -> String {
    match name {
        "type" | "match" | "ref" | "self" | "crate" | "super" | "mod" | "move" => format!("r#{}", name),
        _ => name.to_owned(),
    }
}

/// Emit a Rust parser from the resolved grammar IR.
pub fn emit(grammar: &Grammar) -> Result<String, String> {
    emit_ast(grammar)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rdgen_grammar::compile;

    #[test]
    fn emits_concrete_typed_ast_variants_and_recursive_boxes() {
        let grammar = compile(
            "grammar Expr; expr = value: number => Number(value: value) | left: number, \"+\", right: expr => Add(left: left, right: right); number = digit: \"0\" => Number(digit: digit);",
        ).unwrap();
        let generated = emit_ast(&grammar).unwrap();
        assert!(generated.contains("pub enum Expr"));
        assert!(generated.contains("Number {"));
        assert!(generated.contains("value: Box<Number>"));
        assert!(generated.contains("right: Box<Expr>"));
        assert!(generated.contains("digit: Token"));
    }
}
