#!/usr/bin/env python3
"""Index conformance tests and tutorials by stable, source-derived IDs."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
ids = {}

for path in sorted((root / "tests").glob("*.rs")):
    text = path.read_text()
    if "Conformance groups:" not in text:
        continue
    module = path.stem
    for name in re.findall(r"#\[test\]\s*(?:#\[[^\]]+\]\s*)*fn\s+([A-Za-z0-9_]+)", text):
        test_id = f"test.{module}.{name}"
        if test_id in ids:
            raise SystemExit(f"duplicate conformance ID: {test_id}")
        groups = re.search(r"^// Conformance groups:\s*(.+)$", text, re.MULTILINE).group(1).split(", ")
        ids[test_id] = ("test", module, name, groups, {})

import tomllib
meta = tomllib.loads((root / "tutorial" / "conformance.toml").read_text())
for item in meta["tutorial"]:
    source = Path(item["source"]).with_suffix("").as_posix().replace("/", ".")
    test_id = f"tutorial.{source}"
    if test_id in ids:
        raise SystemExit(f"duplicate conformance ID: {test_id}")
    status = item.get("status", {})
    ids[test_id] = ("tutorial", item["source"], item["name"], ["tutorials"], status)

out = ["# Generated by scripts/index_conformance_tests.py", ""]
for test_id, (kind, source, name, groups, status) in sorted(ids.items()):
    group_text = "[" + ", ".join(f'\"{group}\"' for group in groups) + "]"
    out.append(f'[[test]]\nid = "{test_id}"\nkind = "{kind}"\nsource = "{source}"\nname = "{name}"\ngroups = {group_text}\nstatus = {{ basic = "{status.get("basic", "UNKNOWN")}", c = "{status.get("c", "UNKNOWN")}", jvm = "{status.get("jvm", "UNKNOWN")}" }}\n')
(root / "conformance").mkdir(exist_ok=True)
(root / "conformance" / "test-index.toml").write_text("\n".join(out))
print(f"indexed {len(ids)} conformance tests/tutorials")
