#!/usr/bin/env python3
"""Index conformance tests and tutorials by stable, source-derived IDs."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
ids = {}
valid_statuses = {"PASS", "FAIL", "UNSUPPORTED", "DEFERRED", "UNKNOWN"}
descriptions = {
    "jvm_try_catch_finally_runs_when_available": "Structured TRY/CATCH/FINALLY execution",
    "jvm_catch_filters_and_source_bindings_run_when_available": "Catch filters and source bindings",
    "portable_error_handling_tutorial_runs_when_available": "Portable error-handling tutorial",
    "hello_world_transpiles_assembles_and_runs_when_available": "Hello-world assembly and execution",
    "numeric_literals_and_arithmetic_run_when_available": "Numeric literals and arithmetic",
    "scalar_variables_and_constants_run_when_available": "Scalar variables and constants",
    "structured_branches_and_while_loops_run_when_available": "Structured branches and WHILE loops",
    "scalar_functions_run_when_available": "Scalar function calls and returns",
    "scoped_goto_runs_when_available": "Scoped GOTO labels",
    "jvm_non_integer_arrays_run_when_available": "Typed non-integer arrays and array parameters",
    "c_target_random_file_is_binary_compatible_with_real_bascom_c_writes": "C random-file output is readable by BASCOM",
    "c_target_random_file_is_binary_compatible_with_real_bascom_bascom_writes": "BASCOM random-file output is readable by C",
    "existing_random_access_file_record_usage_still_compiles_on_basic_and_c": "Existing random-file records compile on BASIC and C",
    "jvm_backend_does_not_yet_support_random_access_file_records": "JVM random-file records produce the expected diagnostic",
}

for path in sorted((root / "tests").glob("*.rs")):
    text = path.read_text()
    if "Conformance groups:" not in text:
        continue
    module = path.stem
    for name in re.findall(r"#\[test\]\s*(?:#\[[^\]]+\]\s*)*fn\s+([A-Za-z0-9_]+)", text):
        test_id = f"test.{module}.{name}"
        if test_id in ids:
            raise SystemExit(f"duplicate conformance ID: {test_id}")
        groups = re.search(r"^// Conformance groups:\s*(.+)$", text, re.MULTILINE).group(1).split(", ")
        ids[test_id] = ("test", module, name, groups, {})

import tomllib
meta = tomllib.loads((root / "tutorial" / "conformance.toml").read_text())
for item in meta["tutorial"]:
    source = Path(item["source"]).with_suffix("").as_posix().replace("/", ".")
    test_id = f"tutorial.{source}"
    if test_id in ids:
        raise SystemExit(f"duplicate conformance ID: {test_id}")
    status = dict(item.get("status", {}))
    for backend in ("basic", "c", "jvm"):
        if backend not in status:
            if backend in item.get("na", []) or backend in item.get("wont", []):
                status[backend] = "UNSUPPORTED"
            elif backend in item.get("backends", []):
                status[backend] = "PASS"
            else:
                status[backend] = "DEFERRED"
    invalid = {backend: state for backend, state in status.items() if state.upper() not in valid_statuses}
    if invalid:
        raise SystemExit(f"{test_id}: invalid status values: {invalid}")
    ids[test_id] = ("tutorial", item["source"], item["name"], ["tutorials"], status)

out = ["# Generated by scripts/index_conformance_tests.py", ""]
for test_id, (kind, source, name, groups, status) in sorted(ids.items()):
    group_text = "[" + ", ".join(f'\"{group}\"' for group in groups) + "]"
    description = descriptions.get(name, name).replace('"', '\\"')
    out.append(f'[[test]]\nid = "{test_id}"\nkind = "{kind}"\nsource = "{source}"\nname = "{name}"\ndescription = "{description}"\ngroups = {group_text}\nstatus = {{ basic = "{status.get("basic", "UNKNOWN")}", c = "{status.get("c", "UNKNOWN")}", jvm = "{status.get("jvm", "UNKNOWN")}" }}\n')
(root / "conformance").mkdir(exist_ok=True)
(root / "conformance" / "test-index.toml").write_text("\n".join(out))
print(f"indexed {len(ids)} conformance tests/tutorials")
