#!/usr/bin/env python3
"""Run Cargo conformance tests and record stable per-test outcomes."""
from pathlib import Path
import re
import subprocess

root = Path(__file__).resolve().parents[1]
proc = subprocess.run(
    ["cargo", "test", "--locked", "--", "--color", "never"],
    cwd=root,
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
)
output = proc.stdout
current = "unknown"
results = {}
for line in output.splitlines():
    m = re.search(r"Running tests/([^/]+)\.rs", line)
    if m:
        current = Path(m.group(1)).stem
    m = re.search(r"test ([A-Za-z0-9_]+) \.\.\. (ok|FAILED|ignored)", line)
    if m:
        name, result = m.groups()
        results[f"test.{current}.{name}"] = "PASS" if result == "ok" else ("FAIL" if result == "FAILED" else "DEFERRED")
if proc.returncode != 0:
    print(output)
    raise SystemExit(proc.returncode)
out = ["# Generated by scripts/run_conformance.py", ""]
for test_id, result in sorted(results.items()):
    out.append(f'[[result]]\nid = "{test_id}"\nobserved = "{result}"\n')
(root / "conformance/test-results.toml").write_text("\n".join(out))
print(f"recorded {len(results)} conformance test results")
